### ISSUE TITLE
nr.workflow not respecting filters.

### ISSUE THREAD

**Issue by gcasella** [dmulyalin/salt-nornir#19]
When submitting a workflow using the following

```
main_workflow:
  nr.workflow:
    - options:
        fail_if_any_host_fail_any_step: []
        fail_if_any_host_fail_all_step: []
        fail_if_all_host_fail_any_step: []
        fail_if_all_host_fail_all_step: []
        report_all: False
        filters: {"FB": "ROUTER10"}
        hcache: True
        dcache: False
        sumtable: False
    # define pre-check steps
    - pre_check:
        - name: pre_check_pull_config
          function: nr.nc
          kwargs: {"source": "candidate", "filter": "<configuration><interfaces/></configuration>"}
          args: ["get_config"]
```

It appears the filter is not applied, my nrp that runs this specific host has about 400 managed nodes on it
It will not care about the filter and attempt the workflow across all 400 devices.

I've tried multiple iterations of this filter, tried using FL, FB, FO, and all reported the same issues.
