### ISSUE TITLE
Unable to run nr.cli via netbox external pillar

### ISSUE THREAD

**Issue by abhi1693** [dmulyalin/salt-nornir#25]
My master config for external pillar is

```
ext_pillar:
  - salt_nornir_netbox:
      url: 'http://192.68.100.1'
      token: 'Ggy2Fww1BEy@#dFGvwIv%DB4q!5K@N#Gu2YztTjI'
      use_minion_id_device: False
      use_minion_id_tag: True
      use_hosts_filters: False
      use_pillar: True
      host_add_netbox_data: True
      host_add_interfaces: True
      host_add_interfaces_ip: True
      host_add_interfaces_inventory_items: True
      host_add_connections: True
      secrets:
        resolve_secrets: True
        fetch_username: True
        fetch_password: True
        plugins:
          netbox_secretstore:
            private_key: /home/asaharan/.ssh/id_rsa
```

My pillar on master looks like

```
hosts:
  test:
    salt_nornir_netbox_pillar:
      use_minion_id_tag: true
    groups: [netbox_connection]
nornir:
  actions:
    facts:
      args:
      - show version
      description: Learn device facts
      function: nr.cli
proxy:
  memory_threshold_action: restart
  memory_threshold_mbyte: 2048
  multiprocessing: true
  proxytype: nornir

groups:
  netbox_connection:
    connection_options:
      netbox:
        extras:
          instances:
            production:
              token: Ggy2Fww1BEy@#dFGvwIv%DB4q!5K@N#Gu2YztTjI
              url: 'http://192.68.100.1'

```

The command that I'm trying 

```
salt nb_minion nr.cli 'show clock'
```

Error:

```
nb_minion:
    ----------
    test:
        ----------
        nornir_salt.plugins.tasks.netmiko_send_commands:
            nornir_salt:RetryRunner test - connection netmiko, retry attempt 3, error: ''device_type''
```

salt-nornir version
```
Name: salt-nornir
Version: 0.16.1
Summary: Salt-Nornir Proxy Minion SaltStack Modules
Home-page: https://github.com/dmulyalin/salt-nornir
Author: Denis Mulyalin
Author-email: d.mulyalin@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: nornir, nornir-salt, psutil, pydantic
Required-by:
```

**Comment by abhi1693** [comment]
I could not find anything about `device_type` in the documentation

**Comment by dmulyalin** [comment]
Probably devices somehow ended up without `platform` attribute, which is strange. Could you test it using latest release and also verify inventory content using `nr.nornir inventory` function. Also, maybe running proxy-minion in debug mode would help to collect traceback details.

Also, this pillar data is not required/supported:
```
hosts:
  test:
    salt_nornir_netbox_pillar: <--- remove this
      use_minion_id_tag: true

groups:
  netbox_connection: <--- remove this altogether
    connection_options:
      netbox:
        extras:
          instances:
            production:
              token: Ggy2Fww1BEy@#dFGvwIv%DB4q!5K@N#Gu2YztTjI
              url: 'http://192.68.100.1'
```

instead, to define per-proxy minion Netbox configuration:

```
salt_nornir_netbox_pillar:
  url: 'http://192.68.100.1'
  token: 'Ggy2Fww1BEy@#dFGvwIv%DB4q!5K@N#Gu2YztTjI'
```

Details in [docs](https://salt-nornir.readthedocs.io/en/latest/Nornir%20Netbox%20Pillar%20Module.html#configuration-parameters)
