### ISSUE TITLE
[REQUEST] Add parameter options for Cred Retry to accept different plugins

### ISSUE THREAD

**Issue by gcasella** [dmulyalin/salt-nornir#27]
Hey!

As we discussed on Slack. This is a request to include the logic for looking at different plugin configurations when it comes to the retry runner (credential retry).

this use case is if someone would like to use Public Key Authentication as their primary method instead of Tacacs.
But if public key authentication is not available to still attempt to use Tacacs or local credentials. 

With your help I was able to make this work with napalm only by using;

```
defaults: 
   data: 
      credentials:
         ssh_key_auth:
            username: "rsa-user"
         tacacs_account:
            username: "{{ salt['environ.get']('USERNAME') }}"
            password: "{{ salt['environ.get']('PASSWORD') }}"
            extras:
              optional_args:
                key_file: False
         local_account_1:
            username: admin
            password: "{{ salt['environ.get']('ADMIN_PASSWORD') }}"
            extras:
              optional_args:
                key_file: False
```

What I am suggesting if doable is to add the logic to allow other methods such as ncclient, scrapli_netconf, pyez, etc.

Snippet of the pillar configuration I was thinking of is like this (below is in the json format of the yaml file. apologies for that);

```
'defaults': {
    'data': {
        'credentials': {
            'ssh_key_auth': {
                'username': 'rsa-user'
            },
            'tacacs_account': {
                'username': "user",
                'password': "password",
                'extras': {
                    'napalm': {
                        'optional_args': {
                            'key_file': False
                        },
                    },
                    'scrapli_netconf': {
                        'auth_private_key': None
                    },
                    'ncclient': {
                        'key_filename': None
                    }
                }
            },
```
