### ISSUE TITLE
[FEATURE REQUEST] ability to use job_data kwargs in nr.test

### ISSUE THREAD

**Issue by bodleytunes** [dmulyalin/salt-nornir#32]
Would be great to be able to pass adhoc job_data kwargs dictionary into nr.test to allow the vars to be consumed inside the test suite jinja2

Thanks,
Jon.

**Comment by dmulyalin** [comment]
added support in 0.19.4, please test

**Comment by bodleytunes** [comment]
Awesome will test.

**Comment by bodleytunes** [comment]
I'm not sure if this one is working or if I'm doing something wrong?


```
- check_access_lists:
        - name: We have the new access list entries
          function: nr.test
          kwargs:
            suite: salt://tests/common/acls/arista/acl_validation.j2
            FG: arista
            event_progress: True
            hcache: test_acl_entries
            plugin: scrapli
            job_data: {"access_groups": "test"}
          report: True
          run_if_pass_any: []
```







```
- task: "show ip access-list {{ job_data.access_groups }}"
  test: contains_lines
  pattern:
    {% for acl in acls %}
    - {{ acl }}
    {% endfor %}
  name: ACL Validation (No additional incorrect ACL's are present)
  cli:
    plugin: scrapli

```


`salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'access_groups'; line 17`
