### ISSUE TITLE
[FEATURE REQUEST] - Add support for Nornir PYEZ plugins

### ISSUE THREAD

**Issue by OliElli** [dmulyalin/salt-nornir#34]
I would like to use the Nornir-Pyez plugins found here: https://github.com/DataKnox/nornir_pyez

**Comment by bodleytunes** [comment]
I think you can acheive most of this using the `scrapli_netconf_call` plugin?  isn't pyez just using netconf to call JunOS?

something like:

```
def tacacs_servers_path(*args,**kwargs):
    CONFIG_FILTER = """
    <configuration>
        <system>
            <tacplus-server>
            </tacplus-server>
        </system>
    </configuration>
    """

    nr = __salt__['nornir.get_nornir']()

    # xml flake : Function to transform XML in a flattened python dictionary representation and FILTER its keys using key_filter function
    '''
    processor to filter a list from a nested key at 'nc:rpc-reply'.'nc:data'.configuration.system
    loads xml to dict
    filters dict at specific path (nested key)
    filters out the rest of the dict by using key_filter to select tacacs-servers only
    '''
    flattened_processor = nr.with_processors([
        DataProcessor(
            [
                {"fun": "load_xml"},
                {"fun": "path", "path": "nc:rpc-reply.nc:data.configuration.system"},   
                {"fun": "path", "path": "rpc-reply.data.configuration.system"},  
                {"fun": "key_filter", "pattern": "tacplus-server"}
                #{"fun": "xpath", "expr": "//tacplus-server/name", "rm_ns": True, "recover": True},

            ]
        ),
    ])

    results = flattened_processor.run(
        task=scrapli_netconf_call,
        call="get",
        filter_=CONFIG_FILTER
    )

    return ResultSerializer(results)
```


or for editing storm control settings using scrapli_netconf via task workflow

```
    # Add storm control config
    # storm control config via scrapli netconf
    - add_storm_control_config:
        - name: Add Storm Control Config
          function: nr.nc
          args:
            - "edit_config"
          kwargs:
            target: candidate
            config: salt://templates/common/stp/storm_control/juniper/storm_control_asw.j2
            plugin: scrapli
            event_progress: True
          report: True
```


```
{% set _ = salt['nr.task']('nornir_napalm.plugins.tasks.napalm_get getters=get_interfaces hcache=all_interfaces') %}

{% set all_interfaces = host.all_interfaces['nornir_napalm.plugins.tasks.napalm_get']['result'].get_interfaces -%}

<config>
  <configuration>
    <interfaces>
        {%- for interface in all_interfaces %}
{#            # select only parent interfaces not subinterfaces and only xe and ge interfaces#}
        {%- if "." not in interface and (interface.startswith("xe") or interface.startswith("ge")) %}
      <interface>
        <name>{{ interface }}</name>
        <unit>
          <name>0</name>
          <family>
            <ethernet-switching>
              <recovery-timeout>{{ host.stp.recovery_timeout }}</recovery-timeout>
              <storm-control>sc</storm-control>
            </ethernet-switching>
          </family>
        </unit>
      </interface>
        {%- endif %}
        {%- endfor %}
    </interfaces>
    <forwarding-options>
    <storm-control-profiles>
        <name>{{ host.stp.storm_control_name_default }}</name>
        <all>
        </all>
    </storm-control-profiles>
    <storm-control-profiles>
        <name>{{ host.stp.storm_control_name_sc }}</name>
        <all>
            <bandwidth-level>{{ host.stp.storm_control_name_sc_bandwith_level }}</bandwidth-level>
            <no-unknown-unicast/>
        </all>
        <action-shutdown/>
    </storm-control-profiles>
</forwarding-options>
  </configuration>
</config>
```
