### ISSUE TITLE
Confused with how to use ext_pillar

### ISSUE THREAD

**Issue by bodleytunes** [dmulyalin/salt-nornir#8]
Hi,

I'm trying to generate the inventory in a module using ext_pillar, but every time I try this I get the following in the minion which doesn't start

`No proxy key found in pillar or opts for id nrp1. Check your pillar/opts configuration and contents.  Salt-proxy aborted.`

I've tried returning all sorts but I must be missing something fundamental.

Just wondering what I should be looking at.  As soon as I remover the ext_pillar from master file it starts again and works.

My nrp1.sls is as follows:

```
proxy:
  proxytype: nornir

hosts: {}
groups: {}
defaults: {}
```

and salt master file

```
interface: 0.0.0.0
pki_dir: /etc/salt/pki/master
timeout: 120

file_roots:
  base:
    - /etc/salt/
    - /etc/salt/states/
    - /etc/salt/templates/
    - /etc/salt/_modules

pillar_roots:
  base:
    - /etc/salt/pillar/
    - /etc/salt/states/

ext_pillar:
  - inventory_builder
```

and a snippet of the ext_pillar file (inventory_builder.py) which essentially just returns a dict

```
def ext_pillar(minion_id, pillar, *args, **kwargs):
    _copy_file_from_salt_master(source, destination)
    device_data = inventory_builder_download_data()
    inventory_builder_data_dict = convert_json_to_dict(device_data)
    devices_to_vendors, gen = generate_devices_to_vendors(inventory_builder_data_dict)


    yaml = generate_nornir_style_inventory(devices_to_vendors, gen)
    # create python dictionary from yaml
    inventory_dict = yaml_to_dict(yaml)
    write_inventory_to_file(inventory_dict)

    return inventory_dict
```

**Comment by dmulyalin** [comment]
Wondering how is your `top.sls` file looks like, does it something like:

```yaml
base:
  nrp1:
    - nrp1
```

top.sls must be placed in same folder as nrp1.sls
